#!/bin/bash

test=$1

py=${test%.*}.py

out=${test%.*}.out

python ${py} > ${out} 2> ${out}

if [ -s $out ]; then
    result="FAILED"
else
    result="PASSED"
fi

printf "%-20s  %-10s\n" $py $result

